### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by kanika-codnosticity**
Added another book. It's published by Apress and authored by me(Kanika Sud)
Permalink to Apress book: https://www.apress.com/gp/book/9781484258040

### CODE REVIEW

**Comment by kanika-codnosticity** [comment]
Unable to upload an image of the book(push access denied)

**Review by Nargonath — COMMENTED** [review]
That's weird that you're not having the permission to push the image. Since you push on your own fork you should not have any permission problem. Is there a problem with the unix permission of your file?

Also I cannot checkout your branch locally so there definitely seem to be a problem:
image

Otherwise the text looks good to me.

**Comment by kanika-codnosticity** [comment]
So what should I do?
Ill try once more, by creating one more branch.

**Comment by Nargonath** [comment]
@kanika-codnosticity Disregard the message where I told you I cannot check out your branch. This was due to a branch with the same name as yours on my local repo.

Have you had any luck with your file?

**Comment by kanika-codnosticity** [comment]
Haven't had any luck so far.

Attaching my image within this message. See if you can do so from your end.

I think you will need to rename it according to the html. Let me know if
you are able to uoload, I'll change the html or you can change the file
name

**Comment by Nargonath** [comment]
The image didn't get send through GitHub. You could also upload the image on Imgur and send me the link so I could try to upload it myself.

**Comment by kanika-codnosticity** [comment]
Ok.

**Comment by lloydbenson** [comment]
@kanika-codnosticity just another check in with you here. We'd love to add the resource it just seems like we need some way of getting the image. Let us know if you are still interested in getting this going.

**Comment by kanika-codnosticity** [comment]
Hi,

I'll just added this here. Please rename in html.

https://imgur.com/a/Iox0wQf

Please let me know if you are able to access it.

*Kanika Sud*

Technology | *Codnostic Solutions | www.codnostic.com
<http://www.codnostic.com/>*
Mobile: +918427475945 | Desk: 0172-4181032 | Email: *technology@codnostic.com
<technology@codnostic.com>*

**Comment by Nargonath** [comment]
@kanika-codnosticity I'm able to access it thanks. I'll try to upload your image when I've got some time.

**Comment by kanika-codnosticity** [comment]
Thank you so much!!!

**Comment by Nargonath** [comment]
You're welcome @kanika-codnosticity. 😉

**Pull request merged**
