### PR TITLE
Added hapi-audit-rest plugin

### PR DESCRIPTION
**Pull request by denlap007**
Added new section Auditing and hapi-audit-rest plugin

### CODE REVIEW

**Review by devinivy — COMMENTED** [review]
This looks good to me, though I would expect to see this in the logging section of the page, since it generates a particular type of log.  Would you mind moving it there?

**Comment by denlap007** [comment]
It makes sense too, so feel free to move it. Thanks for the input!

**Comment by denlap007** [comment]
Updated the pull request by moving the plugin to Logging section.

**Review by devinivy — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
