### PR TITLE
corrected JSON

### PR DESCRIPTION
**Pull request by YashGovindani**

### CODE REVIEW

**Comment by Nargonath** [comment]
Please don't spam MR for the same things over and over again.

**Comment by Nargonath** [comment]
Oops my bad sorry. Didn't notice that you actually changed another file. So this is definitely not a spam. I apologize.

Thanks for the contribution but this doesn't need to be fixed as I mentioned in your other MR. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by YashGovindani** [comment]
No problem, I have removed all of my pull requests.

**Comment by Nargonath** [comment]
@YashGovindani You didn't need to close all of them. Some were relevant so I merged them. Thank you.

**Pull request closed without merging**
