### PR TITLE
Correct behaviour of default auth strategy

### LINKED ISSUE #459: Documentation on default auth strategy incorrect?
#### Context

* *node version*: 15.14.0
* *module version*: 20.1.2

#### What are you trying to achieve or the steps to reproduce ?

I'm building an API where all routes are protected by a token based auth strategy. Now I'm trying to register a `/health` route, which should be exempt from the authentication for obvious reasons.

According to the [documentation](https://hapi.dev/tutorials/auth/?lang=en_US#default), defining the route before setting a default auth strategy should yield the desired behaviour:
> Note that any routes added before server.auth.default() is called will not have the default applied to them.

However, with the following code (simplified to the relevant parts), I still get a 401 error when calling the `/health` endpoint:

```js
const tokenScheme = function () {
    return {
        authenticate: async (request, h) => {
            const authorizationHeader = request.headers.authorization;

            const user = await getUser(authorizationHeader);

            if (user) {
                return h.unauthenticated(
                    Boom.unauthorized('Invalid token')'
                );
            }

            return h.authenticated({
                credentials: {
                    user,
                },
            });
        },
    };
};


server.route({
    method: 'GET',
    path: '/health',
    handler: () => {
        return 'up';
    },
});

server.auth.scheme('token', tokenScheme);
server.auth.strategy('token', 'token');
server.auth.default('token');

server.route({
    method: 'GET',
    path: '/user',
    handler: (request) => {
        return request.auth.credentials.user;
    },
});
```

Specifying 
```
options: {
    auth: false,
}
```
on  the `/health` route successfully disables authentication.

I'm unsure whether this is expected behaviour and the documentation is just incorrect, or whether this constitutes a bug. I'm happy to provide a PR for a fix either way, if you can clarify.

### PR DESCRIPTION
**Pull request by lauraseidler**
Fixes #459

### CODE REVIEW

**Review by devinivy — APPROVED** [review]
Thanks!

**Review by Nargonath — APPROVED** [review]
Thanks for the fix! Should we open a follow-up issue to ask for help from the community for an update in the other languages?

**Comment by devinivy** [comment]
@Nargonath that sounds like a good call 👍 .  We could additionally remove the incorrect information from those translations in the interim— I think saying nothing at all about this might be an improvement over the incorrect information.

**Comment by Nargonath** [comment]
Alright. I'll merge this MR then and create 2 new issue: one for the removal and one for "help wanted" on translations.

**Pull request merged**
