### PR TITLE
Update plugins.json

### PR DESCRIPTION
**Pull request by sjyothi54**
Hi Team, 
We have many users on our platform who are using Hapi and would like to instrument it.  We’d love to provide a smooth experience for Hapi users who need to use commercial monitoring solutions.  Please see our [documentation](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/getting-started/introduction-new-relic-nodejs/) here.

Please consider adding a link for your direct users to provide an option for New Relic.  We propose the content submitted in this PR.

### CODE REVIEW

**Review by Nargonath — COMMENTED** [review]
Thank you for your suggestion.

The only problem I see is that the link you provide doesn't actually point to a hapi plugin, which is what this section is all about but rather some documentation. If New Relic doesn't have a specific hapi plugin then it might be better suited to mention the documentation you referred to in the Logging tutorial at the end instead: https://hapi.dev/tutorials/logging/?lang=en_US

**Comment by sjyothi54** [comment]
@Nargonath I had added the New Relic [documentation](https://newrelic.com/instant-observability/hapi/2124da5b-0174-457a-be5a-e0068673b2b5) at the end of Logging tutorial, could you please review this let me know if any modifications need to done.

**Review by Nargonath — APPROVED** [review]
Thank you for the update.

I'll merge it as is but to let you know we started a discussion to rework this section so your link might be moved around but it will still be on the website. 😉

**Comment by Nargonath** [comment]
I released a new version of the website so you can find your modification on the Logging tutorial. 😉

**Comment by sjyothi54** [comment]
@Nargonath Thank you😊

**Pull request merged**
